version: "3"

services:
  catalog_postgres_db:
    image: "postgres:14.0"
    ports:
      - "5439:5432"
    deploy:
      mode: replicated
      replicas: 1
    environment:
      POSTGRES_USER: catalog_db
      POSTGRES_PASSWORD: catalog_db_password
      POSTGRES_DB: catalog_service
    volumes:
      - ./db-data/catalog_postgres_db/:/var/lib/postgresql/data
  order_postgres_db:
    image: "postgres:14.0"
    ports:
      - "5440:5432"
    deploy:
      mode: replicated
      replicas: 1
    environment:
      POSTGRES_USER: order_db
      POSTGRES_PASSWORD: order_db_password
      POSTGRES_DB: order_service
    volumes:
      - ./db-data/order_postgres_db/:/var/lib/postgresql/data